
# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
 
   desc "build Developer app "
   lane :dev_build_ios do |options|
     begin
       build_ios_app(
         export_options: {
           method: "development",
         }
       )
     end
   end
end